# CONFIG_NAME: interop
# PRESET_BASE: interop

PRESET_BASE: mainnet
CONFIG_NAME: testnet

# Genesis
GENESIS_FORK_VERSION: 0x20000089
MIN_GENESIS_TIME: 1400000000
MIN_GENESIS_ACTIVE_VALIDATOR_COUNT: 8

# Altair
ALTAIR_FORK_EPOCH: 2
ALTAIR_FORK_VERSION: 0x20000090

# Merge
BELLATRIX_FORK_EPOCH: 4
BELLATRIX_FORK_VERSION: 0x20000091
TERMINAL_TOTAL_DIFFICULTY: 50

# Capella
CAPELLA_FORK_EPOCH: 6
CAPELLA_FORK_VERSION: 0x20000092
MAX_WITHDRAWALS_PER_PAYLOAD: 4

# Time parameters
SECONDS_PER_SLOT: 6
SLOTS_PER_EPOCH: 4
GENESIS_DELAY: 10

ETH1_FOLLOW_DISTANCE: 8
SHARD_COMMITTEE_PERIOD: 4

# Deposit contract
DEPOSIT_CHAIN_ID: 32382
DEPOSIT_NETWORK_ID: 32382
DEPOSIT_CONTRACT_ADDRESS: 0x4242424242424242424242424242424242424242
